#!/bin/sh
set -eu

APP_DB_PASSWORD="$(cat "$APP_DB_PASSWORD_FILE")"
MIGRATION_DB_PASSWORD="$(cat "$MIGRATION_DB_PASSWORD_FILE")"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
ALTER SYSTEM SET password_encryption = 'scram-sha-256';
CREATE ROLE ${APP_DB_USER} LOGIN PASSWORD '${APP_DB_PASSWORD}' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
CREATE ROLE ${MIGRATION_DB_USER} LOGIN PASSWORD '${MIGRATION_DB_PASSWORD}' NOSUPERUSER CREATEDB NOCREATEROLE;
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${APP_DB_USER}, ${MIGRATION_DB_USER};
GRANT USAGE, CREATE ON SCHEMA public TO ${MIGRATION_DB_USER};
GRANT USAGE ON SCHEMA public TO ${APP_DB_USER};
ALTER DEFAULT PRIVILEGES FOR ROLE ${MIGRATION_DB_USER} IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${APP_DB_USER};
ALTER DEFAULT PRIVILEGES FOR ROLE ${MIGRATION_DB_USER} IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO ${APP_DB_USER};
SQL
